### ISSUE TITLE
Second example in the "quick start" get TypeError: run() got an unexpected keyword argument 'merge_skills'

### ISSUE THREAD

**Issue by littlebeanbean7** [fani-lab/OpeNTF#259]
Hello, 

I am running the 2nd example in the "quick start": python -u main.py -data ../data/raw/dblp/toy.dblp.v12.json -domain dblp -model tbnn tbnn_dt2v_emb

Below is the output and error I get. Please instruct on how to fix it or correctly use your functions. Thank you!

Loading sparse matrices from ./../data/preprocessed/dblp/toy.dblp.v12.json/teamsvecs.pkl ...
Loading indexes pickle from ./../data/preprocessed/dblp/toy.dblp.v12.json/indexes.pkl ...
It took 0.00011920928955078125 seconds to load from the pickles.
It took 0.0004100799560546875 seconds to load the sparse matrices.
Running for (dataset, model): (dblp, tbnn) ... 
Traceback (most recent call last):
  File "main.py", line 210, in <module>
    run(data_list=args.data_list,
  File "main.py", line 167, in run
    m_obj.run(splits, vecs_, indexes, f'{output_path}', settings['model']['baseline'][baseline_name], settings['model']['cmd'], settings['fair'], merge_skills=False)
TypeError: run() got an unexpected keyword argument 'merge_skills'

**Comment by hosseinfani** [comment]
Hi @littlebeanbean7 
For now, the temporal baselines have not integrated to the new pipleline. Though this error has been resolved.

For other non-temporal runs of the baselines in the pipeline, pls refer to 

https://github.com/fani-lab/OpeNTF/blob/main/.github/workflows/
