### ISSUE TITLE
tbnn_dt2v_emb model get error TypeError: train() takes 1 positional argument but 5 were given

### ISSUE THREAD

**Issue by littlebeanbean7** [fani-lab/OpeNTF#261]
When I follow quickstart example and run

python -u main.py -data ../data/raw/dblp/toy.dblp.v12.json -domain dblp -model tbnn_dt2v_emb

I get below error:

Loading sparse matrices from ./../data/preprocessed/dblp/toy.dblp.v12.json/teamsvecs.pkl ...
Loading indexes pickle from ./../data/preprocessed/dblp/toy.dblp.v12.json/indexes.pkl ...
It took 8.249282836914062e-05 seconds to load from the pickles.
It took 0.0004024505615234375 seconds to load the sparse matrices.
Traceback (most recent call last):
  File "main.py", line 210, in <module>
    run(data_list=args.data_list,
  File "main.py", line 154, in run
    t2v.train(emb_setting['d'], emb_setting['w'], emb_setting['dm'], emb_setting['e'])
TypeError: train() takes 1 positional argument but 5 were given

**Comment by littlebeanbean7** [comment]
All of the embedding models (tbnn_dt2v_emb, fnn_emb, tfnn_emb, bnn_emb, tbnn_emb) get the above error

**Comment by hosseinfani** [comment]
Hi @littlebeanbean7 
we made a massive refactor of the codeline but the docs/readme is not ready yet. Sample runs of the pipeline can be seen here, which has been executed successfully as seen at https://github.com/fani-lab/OpeNTF/actions

https://github.com/fani-lab/OpeNTF/blob/main/.github/workflows/*.yml
